code review
shubham-singh/videos.learnfinance.fun pull request #1
Opened 2021-05-05 12:33 UTC by shubham-singh

2021-05-06 09:14 UTC, duhbhavesh reviewed
Hi, @shubham-singh 

This is very well-written code. I've just suggested few minor changes.

2021-05-06 09:14 UTC, duhbhavesh commented on src/Iframe.js
> +const Iframe = ({ video }) => {
[ReactPlayer ](https://www.npmjs.com/package/react-player)component can be used you'll get more features. Btw I liked the idea of creating Iframe component using `iframe`.

2021-05-06 09:14 UTC, duhbhavesh commented on src/index.js
> +    <VideoContextProvider>
I see you've created multiple contexts, I've only one context file. Curious to know why you chose to do that?

2021-05-06 09:14 UTC, duhbhavesh commented on public/index.html
> +<!DOCTYPE html>
Your public folder doesn't have `_redirects` file, it will prevent 404 error on refresh - netlify.

Create a `_redirects` file and add this `/*  /index.html  200`

2021-05-06 09:14 UTC, duhbhavesh commented on src/playlist/playlist.view.js
> +                  src={`https://i.ytimg.com/vi/${video.youtubeId}/mqdefault.jpg`}
instead of getting the `id` of the image, you can get the `image URL from the API? 
this is also a nice hack btw 😅

2021-05-06 09:14 UTC, duhbhavesh commented on src/video/test.db.js
> +// const youtube = {
comments can be removed

2021-05-06 09:50 UTC, shubham-singh commented on src/Iframe.js
> +const Iframe = ({ video }) => {
yaa, i actually saw react player in some of the projects recently. i will end up using that only in future versions.

the problem with iframe is that on mobile it is not auto playing.

2021-05-06 09:51 UTC, shubham-singh commented on src/index.js
> +    <VideoContextProvider>
it's easier to manage and it is easier to read and debug as well. just that

2021-05-06 09:51 UTC, shubham-singh commented on public/index.html
> +<!DOCTYPE html>
ohh i didn't know that. i will add that. thanks :)

2021-05-06 09:55 UTC, shubham-singh commented on src/playlist/playlist.view.js
> +                  src={`https://i.ytimg.com/vi/${video.youtubeId}/mqdefault.jpg`}
i didn't think much into it lol. appending videoID on front end directly was my first chain of thought so i just did that.
the database collection looks clean tho. maybe i will populate imageURL with middleware and then send the data back.

2021-05-06 09:57 UTC, shubham-singh commented on src/video/test.db.js
> +// const youtube = {
thanks for pointing out. i will remove them

2021-05-06 10:55 UTC, duhbhavesh commented on src/index.js
> +    <VideoContextProvider>
Oh Okay!

2021-05-06 14:31 UTC, barbaricankit requested changes
You have written a very clean code.. It was nice to review your code.

2021-05-06 14:31 UTC, barbaricankit commented on src/like/likeButton.js
> +    return likedVideosArr.some((likedVideo) => likedVideo._id === video._id);
you are using some, great to see

2021-05-06 14:31 UTC, barbaricankit commented on src/playlist/addToPlaylist.js
> +  function playlistModal() {
do you really need this function? you are performing a single task in it and also calling the function only one. Just a suggestion..

2021-05-06 14:31 UTC, barbaricankit commented on src/playlist/createPlaylist.js
> +            type: "CREATE_AND_ADD_TO_PLAYLIST",
liked the names you are using for dispatch

2021-05-06 14:31 UTC, barbaricankit commented on src/playlist/playlist.context.js
> +    // playlist: []
remove comments

2021-05-06 14:31 UTC, barbaricankit commented on src/video/video.context.js
> +    // videos: videosList
can remove comments

2021-05-06 14:31 UTC, barbaricankit commented on src/video/videoWatch.js
> +  // const video = videos.find((video) => video._id === id);
remove comments

2021-05-07 17:55 UTC, shubham-singh commented on src/playlist/addToPlaylist.js
> +  function playlistModal() {
i actually don't. i don't know why i wrote that. thanks for pointing out ankit :)

2021-05-09 10:02 UTC, duhbhavesh commented
Looks good

2021-05-09 12:37 UTC, barbaricankit commented
Looks good.

2021-09-15 07:13 UTC, merged